name: SBOM Demo

on:
  workflow_dispatch:

jobs:
  
  create-sbom:
  
    runs-on: ubuntu-latest

  
    steps:
  
    - name: Generate SBOM
      id: gensbom
      uses: advanced-security/generate-sbom-action@v1
      
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}
